# Header
menu:
  Főoldal: /
  Archívum: /archives
rss: /atom.xml

# Content
excerpt_link: Olvass tovább! →
fancybox: true

# Sidebar
widgets:
- search
- tag
- tagcloud

# Miscellaneous
google_analytics:
favicon:
twitter:
google_plus:
fb_admins:
fb_app_id:
